### ISSUE TITLE
Release Checklist - v0.7

### ISSUE THREAD

**Issue by TonyGrif** [TonyGrif/15-puzzle-solver#20]
Tasks required for v0.7

## Features
- [ ] Update board starting state entry to operate via a TUI (can still pass string as optional argument)
- [ ] Add TUI for playing this application

## Fixes
- [ ] Update logger to create module specific ones

## Docs
- [ ] Update Board class docstring to include methods

## CI/CD
- [ ] Automated release publishing with wheel file published
